import Head from 'next/head'
import Image from 'next/image'
import ParticlesBack from "../components/ParticleBackground";
import {Box, Center} from "@chakra-ui/react";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <ParticlesBack />




    </div>
  )
}
